{# #############################################################################
# This file compiles to Dockerfile.
############################################################################ -#}
#
# This file compiled from Dockerfile.in.
#

{% set current_dockerfile_config = dockerfile.main -%}

FROM {{ current_dockerfile_config.base_image }}

{# #############################################################################
# Core configuration of the environment. We should always include these.
############################################################################ -#}
{% include 'base/dockerfile/environment.Dockerfile' %}

{% include 'base/dockerfile/apt-get-essentials.Dockerfile' %}

{# #############################################################################
# Different runtimes we may want to include.
#
# {% include 'base/dockerfile/python.Dockerfile' %}
# {% include 'base/dockerfile/ruby.Dockerfile' %}
# {% include 'base/dockerfile/node.Dockerfile' %}
############################################################################ -#}
{% include 'base/dockerfile/python.Dockerfile' %}

################################################################################
# Expose any ports or persistent volumes.
################################################################################

# Port where we listen
EXPOSE 8080

################################################################################
# Set up our entrypoint script.
################################################################################
COPY docker-pyramid-site/docker-pyramid-site-entrypoint.sh /docker-pyramid-site-entrypoint.sh
RUN dos2unix /docker-pyramid-site-entrypoint.sh && \
    chmod +x /docker-pyramid-site-entrypoint.sh

# Run the wrapper script
CMD ["/docker-pyramid-site-entrypoint.sh"]
{# This comment gives us a newline at the end of the generated file #}
